In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/competitions/playground-series-s6e7/sample_submission.csv
/kaggle/input/competitions/playground-series-s6e7/train.csv
/kaggle/input/competitions/playground-series-s6e7/test.csv

In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, f1_score
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder

from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from xgboost import XGBClassifier

In [3]:
train = pd.read_csv("/kaggle/input/competitions/playground-series-s6e7/train.csv")
test = pd.read_csv("/kaggle/input/competitions/playground-series-s6e7/test.csv")

train.head()

,id,health_condition,sleep_duration,heart_rate,bmi,calorie_expenditure,step_count,exercise_duration,water_intake,diet_type,stress_level,sleep_quality,physical_activity_level,smoking_alcohol,gender
0,0,unhealthy,5.22,70.6,25.66,2174.0,1326.0,19.8,1.86,veg,high,average,sedentary,yes,female
1,1,at-risk,5.53,71.3,25.84,1966.0,9891.0,49.9,1.26,non-veg,low,average,moderate,yes,other
2,2,unhealthy,5.29,75.4,24.54,2688.0,14216.0,38.1,1.60,veg,high,poor,active,yes,male
3,3,unhealthy,4.70,77.2,23.13,2630.0,7174.0,59.9,2.02,veg,high,average,active,occasional,female
4,4,at-risk,7.23,73.4,28.44,2560.0,6584.0,46.0,2.25,veg,NaN,average,sedentary,NaN,male

In [4]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690088 entries, 0 to 690087
Data columns (total 15 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id                       690088 non-null  int64
 1   health_condition         690088 non-null  object
 2   sleep_duration           614089 non-null  float64
 3   heart_rate               682255 non-null  float64
 4   bmi                      676190 non-null  float64
 5   calorie_expenditure      637235 non-null  float64
 6   step_count               676172 non-null  float64
 7   exercise_duration        683187 non-null  float64
 8   water_intake             646611 non-null  float64
 9   diet_type                683187 non-null  object
 10  stress_level             607277 non-null  object
 11  sleep_quality            631757 non-null  object
 12  physical_activity_level  653467 non-null  object
 13  smoking_alcohol          661506 non-null  object
 14  gender                   668715 non-null  object
dtypes: float64(7), int64(1), object(7)
memory usage: 79.0+ MB

In [5]:
train.health_condition.unique()

array(['unhealthy', 'at-risk', 'fit'], dtype=object)

In [6]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 295753 entries, 0 to 295752
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id                       295753 non-null  int64
 1   sleep_duration           263182 non-null  float64
 2   heart_rate               292396 non-null  float64
 3   bmi                      289797 non-null  float64
 4   calorie_expenditure      273101 non-null  float64
 5   step_count               289789 non-null  float64
 6   exercise_duration        292795 non-null  float64
 7   water_intake             277120 non-null  float64
 8   diet_type                292795 non-null  object
 9   stress_level             260263 non-null  object
 10  sleep_quality            270754 non-null  object
 11  physical_activity_level  280058 non-null  object
 12  smoking_alcohol          283504 non-null  object
 13  gender                   286593 non-null  object
dtypes: float64(7), int64(1), object(6)
memory usage: 31.6+ MB

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
train.groupby('health_condition')['id'].count()

health_condition
at-risk      592561
fit           39803
unhealthy     57724
Name: id, dtype: int64

In [9]:
x, y = train.drop(columns=['id', 'health_condition'], axis=1), train[['health_condition']]
x.head()

,sleep_duration,heart_rate,bmi,calorie_expenditure,step_count,exercise_duration,water_intake,diet_type,stress_level,sleep_quality,physical_activity_level,smoking_alcohol,gender
0,5.22,70.6,25.66,2174.0,1326.0,19.8,1.86,veg,high,average,sedentary,yes,female
1,5.53,71.3,25.84,1966.0,9891.0,49.9,1.26,non-veg,low,average,moderate,yes,other
2,5.29,75.4,24.54,2688.0,14216.0,38.1,1.60,veg,high,poor,active,yes,male
3,4.70,77.2,23.13,2630.0,7174.0,59.9,2.02,veg,high,average,active,occasional,female
4,7.23,73.4,28.44,2560.0,6584.0,46.0,2.25,veg,NaN,average,sedentary,NaN,male

In [10]:
y.head()

  health_condition
0        unhealthy
1          at-risk
2        unhealthy
3        unhealthy
4          at-risk

In [11]:
cat_features = x.columns[np.where(x.dtypes != float)[0]].values.tolist()
print(cat_features)

# make sure that the categorical features are encoded as strings
x[cat_features] = x[cat_features].astype(str)

['diet_type', 'stress_level', 'sleep_quality', 'physical_activity_level', 'smoking_alcohol', 'gender']

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42, stratify=y)

In [13]:
x_test.head()

,sleep_duration,heart_rate,bmi,calorie_expenditure,step_count,exercise_duration,water_intake,diet_type,stress_level,sleep_quality,physical_activity_level,smoking_alcohol,gender
304516,6.82,67.9,27.17,2464.0,13456.0,39.9,2.05,veg,medium,good,moderate,no,other
165358,7.97,92.9,16.86,NaN,7456.0,26.9,2.14,balanced,high,good,moderate,no,female
671841,NaN,NaN,22.18,2352.0,4140.0,19.7,2.33,non-veg,low,poor,sedentary,occasional,male
403460,NaN,83.1,21.93,2620.0,11656.0,41.1,1.22,non-veg,medium,good,moderate,occasional,other
351133,8.14,80.0,23.41,2442.0,4484.0,38.9,2.32,veg,medium,nan,sedentary,no,other

In [14]:
model = CatBoostClassifier(
    iterations=100,
    depth=6,
    learning_rate=0.1,
    loss_function='MultiClass',
    task_type = 'GPU',
    devices = '0'
)
model.fit(x_train, y_train, cat_features=cat_features)

0:	learn: 0.9660086	total: 6.49s	remaining: 10m 42s
1:	learn: 0.8655135	total: 6.5s	remaining: 5m 18s
2:	learn: 0.7861504	total: 6.52s	remaining: 3m 30s
3:	learn: 0.7215640	total: 6.53s	remaining: 2m 36s
4:	learn: 0.6680332	total: 6.54s	remaining: 2m 4s
5:	learn: 0.6232842	total: 6.55s	remaining: 1m 42s
6:	learn: 0.5852682	total: 6.57s	remaining: 1m 27s
7:	learn: 0.5528050	total: 6.58s	remaining: 1m 15s
8:	learn: 0.5246116	total: 6.59s	remaining: 1m 6s
9:	learn: 0.5002170	total: 6.61s	remaining: 59.5s
10:	learn: 0.4549014	total: 6.62s	remaining: 53.6s
11:	learn: 0.4172772	total: 6.63s	remaining: 48.6s
12:	learn: 0.3855128	total: 6.64s	remaining: 44.5s
13:	learn: 0.3583159	total: 6.66s	remaining: 40.9s
14:	learn: 0.3343723	total: 6.67s	remaining: 37.8s
15:	learn: 0.3137364	total: 6.68s	remaining: 35.1s
16:	learn: 0.2954340	total: 6.7s	remaining: 32.7s
17:	learn: 0.2794770	total: 6.71s	remaining: 30.6s
18:	learn: 0.2651512	total: 6.72s	remaining: 28.7s
19:	learn: 0.2526537	total: 6.73s	remaining: 26.9s
20:	learn: 0.2413865	total: 6.75s	remaining: 25.4s
21:	learn: 0.2312647	total: 6.76s	remaining: 24s
22:	learn: 0.2160866	total: 6.78s	remaining: 22.7s
23:	learn: 0.2030849	total: 6.79s	remaining: 21.5s
24:	learn: 0.1917769	total: 6.8s	remaining: 20.4s
25:	learn: 0.1819640	total: 6.81s	remaining: 19.4s
26:	learn: 0.1729425	total: 6.82s	remaining: 18.4s
27:	learn: 0.1653773	total: 6.83s	remaining: 17.6s
28:	learn: 0.1583203	total: 6.85s	remaining: 16.8s
29:	learn: 0.1521367	total: 6.86s	remaining: 16s
30:	learn: 0.1466568	total: 6.87s	remaining: 15.3s
31:	learn: 0.1418793	total: 6.88s	remaining: 14.6s
32:	learn: 0.1374525	total: 6.9s	remaining: 14s
33:	learn: 0.1335939	total: 6.91s	remaining: 13.4s
34:	learn: 0.1301652	total: 6.92s	remaining: 12.9s
35:	learn: 0.1271613	total: 6.94s	remaining: 12.3s
36:	learn: 0.1243767	total: 6.95s	remaining: 11.8s
37:	learn: 0.1220254	total: 6.96s	remaining: 11.4s
38:	learn: 0.1197842	total: 6.97s	remaining: 10.9s
39:	learn: 0.1179362	total: 6.99s	remaining: 10.5s
40:	learn: 0.1160510	total: 7s	remaining: 10.1s
41:	learn: 0.1146297	total: 7.01s	remaining: 9.68s
42:	learn: 0.1130531	total: 7.02s	remaining: 9.31s
43:	learn: 0.1117464	total: 7.04s	remaining: 8.96s
44:	learn: 0.1106776	total: 7.05s	remaining: 8.62s
45:	learn: 0.1095275	total: 7.06s	remaining: 8.29s
46:	learn: 0.1086003	total: 7.07s	remaining: 7.98s
47:	learn: 0.1077364	total: 7.08s	remaining: 7.67s
48:	learn: 0.1068836	total: 7.1s	remaining: 7.39s
49:	learn: 0.1061284	total: 7.11s	remaining: 7.11s
50:	learn: 0.1053232	total: 7.12s	remaining: 6.84s
51:	learn: 0.1046335	total: 7.13s	remaining: 6.58s
52:	learn: 0.1040603	total: 7.15s	remaining: 6.34s
53:	learn: 0.1035557	total: 7.16s	remaining: 6.1s
54:	learn: 0.1031152	total: 7.17s	remaining: 5.87s
55:	learn: 0.1026348	total: 7.18s	remaining: 5.64s
56:	learn: 0.1021663	total: 7.19s	remaining: 5.43s
57:	learn: 0.1018052	total: 7.21s	remaining: 5.22s
58:	learn: 0.1013866	total: 7.22s	remaining: 5.02s
59:	learn: 0.1010528	total: 7.23s	remaining: 4.82s
60:	learn: 0.1007774	total: 7.24s	remaining: 4.63s
61:	learn: 0.1003106	total: 7.25s	remaining: 4.45s
62:	learn: 0.0998672	total: 7.27s	remaining: 4.27s
63:	learn: 0.0995179	total: 7.28s	remaining: 4.09s
64:	learn: 0.0992511	total: 7.29s	remaining: 3.93s
65:	learn: 0.0989675	total: 7.3s	remaining: 3.76s
66:	learn: 0.0987252	total: 7.32s	remaining: 3.6s
67:	learn: 0.0984813	total: 7.33s	remaining: 3.45s
68:	learn: 0.0982508	total: 7.34s	remaining: 3.3s
69:	learn: 0.0980399	total: 7.35s	remaining: 3.15s
70:	learn: 0.0978823	total: 7.37s	remaining: 3.01s
71:	learn: 0.0977114	total: 7.38s	remaining: 2.87s
72:	learn: 0.0975701	total: 7.39s	remaining: 2.73s
73:	learn: 0.0973899	total: 7.4s	remaining: 2.6s
74:	learn: 0.0972788	total: 7.41s	remaining: 2.47s
75:	learn: 0.0971249	total: 7.42s	remaining: 2.34s
76:	learn: 0.0970089	total: 7.44s	remaining: 2.22s
77:	learn: 0.0967815	total: 7.45s	remaining: 2.1s
78:	learn: 0.0965116	total: 7.46s	remaining: 1.98s
79:	learn: 0.0964184	total: 7.47s	remaining: 1.87s
80:	learn: 0.0963266	total: 7.48s	remaining: 1.75s
81:	learn: 0.0961872	total: 7.5s	remaining: 1.65s
82:	learn: 0.0960381	total: 7.51s	remaining: 1.54s
83:	learn: 0.0959614	total: 7.52s	remaining: 1.43s
84:	learn: 0.0958419	total: 7.53s	remaining: 1.33s
85:	learn: 0.0958178	total: 7.54s	remaining: 1.23s
86:	learn: 0.0957467	total: 7.56s	remaining: 1.13s
87:	learn: 0.0956064	total: 7.57s	remaining: 1.03s
88:	learn: 0.0955424	total: 7.58s	remaining: 937ms
89:	learn: 0.0954731	total: 7.59s	remaining: 844ms
90:	learn: 0.0952567	total: 7.6s	remaining: 752ms
91:	learn: 0.0951427	total: 7.62s	remaining: 662ms
92:	learn: 0.0949833	total: 7.63s	remaining: 574ms
93:	learn: 0.0948704	total: 7.64s	remaining: 488ms
94:	learn: 0.0947803	total: 7.66s	remaining: 403ms
95:	learn: 0.0947310	total: 7.67s	remaining: 320ms
96:	learn: 0.0946919	total: 7.68s	remaining: 238ms
97:	learn: 0.0945976	total: 7.69s	remaining: 157ms
98:	learn: 0.0945537	total: 7.7s	remaining: 77.8ms
99:	learn: 0.0944644	total: 7.71s	remaining: 0us

CatBoostClassifier(depth=6, devices='0', iterations=100, learning_rate=0.1, loss_function='MultiClass', task_type='GPU')

In [15]:
y_pred = model.predict(x_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.966076888521787

In [16]:
final_model = model = CatBoostClassifier(
    iterations=100,
    depth=6,
    learning_rate=0.1,
    loss_function='MultiClass',
    task_type = 'GPU',
    devices = '0'
)
final_model.fit(x, y, cat_features=cat_features)

0:	learn: 0.9659830	total: 14.3ms	remaining: 1.42s
1:	learn: 0.8654123	total: 27.9ms	remaining: 1.37s
2:	learn: 0.7861093	total: 41.2ms	remaining: 1.33s
3:	learn: 0.7214788	total: 54.1ms	remaining: 1.3s
4:	learn: 0.6679443	total: 68.5ms	remaining: 1.3s
5:	learn: 0.6232460	total: 81.4ms	remaining: 1.27s
6:	learn: 0.5850281	total: 94.2ms	remaining: 1.25s
7:	learn: 0.5527049	total: 107ms	remaining: 1.23s
8:	learn: 0.5245660	total: 120ms	remaining: 1.21s
9:	learn: 0.5000658	total: 132ms	remaining: 1.19s
10:	learn: 0.4548162	total: 145ms	remaining: 1.18s
11:	learn: 0.4171568	total: 159ms	remaining: 1.17s
12:	learn: 0.3856770	total: 173ms	remaining: 1.16s
13:	learn: 0.3585130	total: 186ms	remaining: 1.14s
14:	learn: 0.3348320	total: 199ms	remaining: 1.13s
15:	learn: 0.3139277	total: 212ms	remaining: 1.11s
16:	learn: 0.2959840	total: 226ms	remaining: 1.1s
17:	learn: 0.2798883	total: 239ms	remaining: 1.09s
18:	learn: 0.2652146	total: 252ms	remaining: 1.07s
19:	learn: 0.2526426	total: 265ms	remaining: 1.06s
20:	learn: 0.2416001	total: 278ms	remaining: 1.05s
21:	learn: 0.2261684	total: 291ms	remaining: 1.03s
22:	learn: 0.2119889	total: 304ms	remaining: 1.02s
23:	learn: 0.1997110	total: 318ms	remaining: 1s
24:	learn: 0.1889864	total: 331ms	remaining: 992ms
25:	learn: 0.1796832	total: 344ms	remaining: 978ms
26:	learn: 0.1710601	total: 357ms	remaining: 964ms
27:	learn: 0.1637711	total: 370ms	remaining: 951ms
28:	learn: 0.1570125	total: 383ms	remaining: 938ms
29:	learn: 0.1514071	total: 396ms	remaining: 924ms
30:	learn: 0.1465261	total: 409ms	remaining: 910ms
31:	learn: 0.1417770	total: 422ms	remaining: 897ms
32:	learn: 0.1377042	total: 437ms	remaining: 887ms
33:	learn: 0.1338566	total: 451ms	remaining: 875ms
34:	learn: 0.1303753	total: 464ms	remaining: 861ms
35:	learn: 0.1274914	total: 478ms	remaining: 850ms
36:	learn: 0.1248318	total: 491ms	remaining: 836ms
37:	learn: 0.1227633	total: 505ms	remaining: 824ms
38:	learn: 0.1203646	total: 518ms	remaining: 810ms
39:	learn: 0.1183005	total: 531ms	remaining: 797ms
40:	learn: 0.1166992	total: 545ms	remaining: 784ms
41:	learn: 0.1150307	total: 558ms	remaining: 771ms
42:	learn: 0.1134719	total: 572ms	remaining: 758ms
43:	learn: 0.1124123	total: 585ms	remaining: 744ms
44:	learn: 0.1110828	total: 598ms	remaining: 731ms
45:	learn: 0.1102594	total: 611ms	remaining: 717ms
46:	learn: 0.1092595	total: 623ms	remaining: 703ms
47:	learn: 0.1083021	total: 636ms	remaining: 689ms
48:	learn: 0.1075545	total: 649ms	remaining: 676ms
49:	learn: 0.1067684	total: 662ms	remaining: 662ms
50:	learn: 0.1061778	total: 675ms	remaining: 649ms
51:	learn: 0.1055312	total: 688ms	remaining: 635ms
52:	learn: 0.1048576	total: 702ms	remaining: 622ms
53:	learn: 0.1042658	total: 715ms	remaining: 609ms
54:	learn: 0.1037735	total: 728ms	remaining: 596ms
55:	learn: 0.1032796	total: 743ms	remaining: 583ms
56:	learn: 0.1029842	total: 757ms	remaining: 571ms
57:	learn: 0.1024396	total: 771ms	remaining: 558ms
58:	learn: 0.1019552	total: 785ms	remaining: 546ms
59:	learn: 0.1015043	total: 798ms	remaining: 532ms
60:	learn: 0.1009214	total: 812ms	remaining: 519ms
61:	learn: 0.1004498	total: 825ms	remaining: 506ms
62:	learn: 0.1000271	total: 839ms	remaining: 493ms
63:	learn: 0.0996729	total: 853ms	remaining: 480ms
64:	learn: 0.0993651	total: 866ms	remaining: 466ms
65:	learn: 0.0990745	total: 878ms	remaining: 453ms
66:	learn: 0.0988969	total: 891ms	remaining: 439ms
67:	learn: 0.0986513	total: 904ms	remaining: 425ms
68:	learn: 0.0985042	total: 916ms	remaining: 412ms
69:	learn: 0.0982304	total: 930ms	remaining: 399ms
70:	learn: 0.0979716	total: 943ms	remaining: 385ms
71:	learn: 0.0978659	total: 956ms	remaining: 372ms
72:	learn: 0.0976874	total: 969ms	remaining: 358ms
73:	learn: 0.0974759	total: 982ms	remaining: 345ms
74:	learn: 0.0973374	total: 995ms	remaining: 332ms
75:	learn: 0.0972281	total: 1.01s	remaining: 318ms
76:	learn: 0.0971396	total: 1.02s	remaining: 305ms
77:	learn: 0.0969193	total: 1.03s	remaining: 291ms
78:	learn: 0.0967318	total: 1.05s	remaining: 278ms
79:	learn: 0.0965613	total: 1.06s	remaining: 265ms
80:	learn: 0.0964314	total: 1.07s	remaining: 252ms
81:	learn: 0.0962954	total: 1.09s	remaining: 239ms
82:	learn: 0.0961287	total: 1.1s	remaining: 225ms
83:	learn: 0.0959599	total: 1.11s	remaining: 212ms
84:	learn: 0.0958235	total: 1.13s	remaining: 199ms
85:	learn: 0.0956918	total: 1.14s	remaining: 185ms
86:	learn: 0.0955894	total: 1.15s	remaining: 172ms
87:	learn: 0.0955219	total: 1.17s	remaining: 159ms
88:	learn: 0.0954471	total: 1.18s	remaining: 146ms
89:	learn: 0.0953209	total: 1.19s	remaining: 132ms
90:	learn: 0.0952490	total: 1.2s	remaining: 119ms
91:	learn: 0.0951875	total: 1.22s	remaining: 106ms
92:	learn: 0.0951521	total: 1.23s	remaining: 92.5ms
93:	learn: 0.0951097	total: 1.24s	remaining: 79.2ms
94:	learn: 0.0950565	total: 1.25s	remaining: 66ms
95:	learn: 0.0949239	total: 1.27s	remaining: 52.8ms
96:	learn: 0.0948163	total: 1.28s	remaining: 39.6ms
97:	learn: 0.0947278	total: 1.29s	remaining: 26.4ms
98:	learn: 0.0946465	total: 1.31s	remaining: 13.2ms
99:	learn: 0.0946008	total: 1.32s	remaining: 0us

CatBoostClassifier(depth=6, devices='0', iterations=100, learning_rate=0.1, loss_function='MultiClass', task_type='GPU')

In [17]:
final_test = test.drop(columns=['id'], axis=1)
final_test = final_test['water_intake'].fillna(2.19)
pred = final_model.predict(final_test)

submission = pd.DataFrame({
    "id": test["id"],
    "health_condition": pred
})

# Save to CSV without the index
submission.to_csv('submission.csv', index=False)
print("Submission file saved successfully!")

CatBoostError: Invalid type for cat_feature[non-default value idx=0,feature_idx=7]=1.14 : cat_features must be integer or string, real number values and NaN values should be converted to string.

In [22]:
final_test.iloc[6:8]

6    2.01
7    1.14
Name: water_intake, dtype: float64

In [ ]:
test['water_intake'].mean()

In [ ]:
test[cat_features] = test[cat_features].astype(str)

pred = final_model.predict(test.drop(columns=['id'], axis=1))

submission = pd.DataFrame({
    "id": test["id"],
    "health_condition": pred
})

# Save to CSV without the index
submission.to_csv('submission.csv', index=False)
print("Submission file saved successfully!")

In [ ]:
test[cat_features] = test[cat_features].astype(str)
test.info()

In [ ]:
cat_features

In [ ]:
test[cat_features].astype(str).info()